### ISSUE TITLE
Stalenodes is broken with Chef 11.8.2 and Ruby 1.9.3-p484

### ISSUE THREAD

**Issue by siris** [paulmooring/knife-stalenodes#2]
Hi there,

Recently upgrade to Chef 11.8.2 running on top of Ruby 1.9.3-p484. Unfortunately knife-stalenodes seems to be broken. Here is the error I am getting:

```
# knife stalenodes -V
ERROR: Connection refused connecting to /search/node?q=ohai_time:[*%20TO%201386737216]&sort=X_CHEF_id_CHEF_X%20asc&start=0&rows=2500, retry 1/5
ERROR: Connection refused connecting to /search/node?q=ohai_time:[*%20TO%201386737216]&sort=X_CHEF_id_CHEF_X%20asc&start=0&rows=2500, retry 2/5
ERROR: Connection refused connecting to /search/node?q=ohai_time:[*%20TO%201386737216]&sort=X_CHEF_id_CHEF_X%20asc&start=0&rows=2500, retry 3/5
ERROR: Connection refused connecting to /search/node?q=ohai_time:[*%20TO%201386737216]&sort=X_CHEF_id_CHEF_X%20asc&start=0&rows=2500, retry 4/5
ERROR: Connection refused connecting to /search/node?q=ohai_time:[*%20TO%201386737216]&sort=X_CHEF_id_CHEF_X%20asc&start=0&rows=2500, retry 5/5
ERROR: Network Error: Connection refused - Connection refused connecting to /search/node?q=ohai_time:[*%20TO%201386737216]&sort=X_CHEF_id_CHEF_X%20asc&start=0&rows=2500, giving up
Check your knife configuration and network settings
```

**Comment by paulmooring** [comment]
Thanks for reporting this.  Should just be a simple change of a config attribute.  I pushed a new gem (version 1.10) with a fix.

**Comment by siris** [comment]
Paul you are awesome. Tested and stalenodes is now working great with Chef
11.8.2

Thank you,
Shane

On Tue, Dec 10, 2013 at 11:13 PM, Paul Mooring notifications@github.comwrote:

> Thanks for reporting this. Should just be a simple change of a config
> attribute. I pushed a new gem (version 1.10) with a fix.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/paulmooring/knife-stalenodes/issues/2#issuecomment-30299312
> .

## 

Shane R. Sofos | ssofos@gmail.com | www.shanesofos.com
